yolo_model:

  config_file:
    name: yolo3-6.cfg
  weight_file:
    name: yolo3-6.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - BLUECUP
      - BUNNY_PLUSHIE 
      - FOAMFISH 
      - BISCUIT 
      - SHAMPOO 
      - FIRETRUCK
